title: Maldini
email: contact@nmbhrd.xyz
description: >
    personal website.
baseurl: ""
url: "https://nmbhrd.xyz" # the base hostname & protocol for your site
github_username: nmbhrd

markdown: kramdown
